# Generated by Django 3.1.4 on 2021-02-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='credits',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='registrationNumber',
            field=models.TextField(max_length=50),
        ),
    ]
