# Generated by Django 3.1.4 on 2021-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_auto_20210224_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='registrationNumber',
            field=models.CharField(max_length=50),
        ),
    ]
